name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Windows binaries
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Exiter.csproj

      - name: Publish self-contained (Release)
        run: dotnet publish Exiter.csproj -c Release -r win-x64 --self-contained true

      - name: Publish framework-dependent (ReleaseFDD)
        run: dotnet publish Exiter.csproj -c ReleaseFDD -r win-x64 --self-contained false

      - name: Prepare artifacts
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          Copy-Item "bin/Release/net8.0-windows/win-x64/publish/Exiter.exe" "artifacts/Exiter-$tag-win-x64-selfcontained.exe"
          Copy-Item "bin/ReleaseFDD/net8.0-windows/win-x64/publish/Exiter.exe" "artifacts/Exiter-$tag-win-x64-frameworkdependent.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exiter-${{ github.ref_name }}-win-x64
          path: artifacts/*.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: exiter-${{ github.ref_name }}-win-x64
          path: artifacts

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
